### ISSUE TITLE
COS code snippets

### ISSUE THREAD

**Issue by ZitRos** [eduard93/Utils#1]
Eduard, COS code snippets is a very great idea, and I though about it.

But generally for snippets we have [GitHub's gist](https://gist.github.com/). What about corporate intersystems-ru gist? This will enable search over common programmers tasks in Caché.

What do you think?

**Comment by eduard93** [comment]
I use this set of utilities across wide range of instances so  Gist functionality is ultimately lacking for this use case.

**Comment by eduard93** [comment]
Also, ckeck out https://code.intersystems.com/ for more code snippets

**Comment by ZitRos** [comment]
> Also, check out https://code.intersystems.com/ for more code snippets

Wow, such a great resource dedicated to ISC products code snippets. Why I still do not know about it? Joining :)

**Comment by ZitRos** [comment]
The only thing left is to make it fully googleable and speedy, well-designed and featured. Is there a developer of this site?

**Comment by eduard93** [comment]
Try to make it your summer project :+1: Last summer one of interns modernized it.

**Comment by ZitRos** [comment]
So development stopped?

**Comment by eduard93** [comment]
AFAIK Yes
