### ISSUE TITLE
Convert the code to UDL?

### ISSUE THREAD

**Issue by evshvarov** [eduard93/Utils#2]

**Comment by evshvarov** [comment]
Up, cause Github now recognizes ObjectScript. And maybe add Open Exchange entry for this too?

**Comment by eduard93** [comment]
> Open Exchange entry

Definitely not. I do not endorse the use of this repository.

I'll convert to udl.

**Comment by evshvarov** [comment]
Up ) And do you mind if I steal some functions and publish on OEX-ZPM?

**Comment by eduard93** [comment]
Feel free

**Comment by evshvarov** [comment]
Done
